[tool.poetry]
name = "dev_help"
version = "0.0.1"
description = ""
authors = ["vikketii, otahontas"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
starlette = "^0.13.8"
uvicorn = "^0.11.8"
aiofiles = "^0.5.0"
python-multipart = "^0.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"