[tool.poetry]
name = "dev_help"
version = "0.0.1"
description = ""
authors = ["vikketii, otahontas"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
starlette = "^0.13.8"
uvicorn = "^0.11.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
server = "dev_help.server:main"
