name: Server code style check
on:
  push:
    paths:
      - 'packages/server/**'

jobs:
  code_style:
    name: Check formatting with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Lint with flake8
        run: cd packages/server && nox -s lint_check
      - name: Format with black
        run: cd packages/server && nox -s format_check
